
[[constraint]]
  name = "github.com/Clever/amazon-kinesis-client-go"
  version = "1.0.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.38.0"

[[constraint]]
  name = "github.com/eapache/go-resiliency"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  branch = "master"
  name = "github.com/signalfx/golib"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.25.0"
