[[constraint]]
  branch = "master"
  name = "github.com/Clever/amazon-kinesis-client-go"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  branch = "master"
  name = "github.com/signalfx/golib"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  version = "^6.12.0"
  name = "gopkg.in/Clever/kayvee-go.v6"

[[constraint]]
  version = "1.1.0"
  name = "github.com/eapache/go-resiliency"
