routes:
  unknown-error-alerts:
    matchers:
      title: ["stats"]
      unknown-error: [ "*" ]
    output:
      type: "alerts"
      series: "kinesis-consumer.alerts.unknown-error"
      dimensions: [ ]
      value_field: "unknown-error" 
      stat_type: "counter"
  log-volume-send-failure:
    matchers:
      title: ["failed-sending-volumes"]
    output:
      type: "notifications"
      channel: "#eng-infra-alerts-minor"
      icon: ":signalfx:"
      user: "kinesis-alerts-consumer"
      message: "Error sending log volumes: ```%{error}```"
  cloudwatch-errors:
    matchers:
      title: ["error-sending-to-cloudwatch"]
    output:
      type: "alerts"
      series: "kinesis-consumer.alerts.cloudwatch-error"
      dimensions: [ ]
      stat_type: "counter"

